# Generated by Django 2.0.1 on 2018-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='hash',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
